//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekerJob
{
    using System;
    using System.Collections.Generic;
    
    public partial class InforCandidate
    {
        public string username { get; set; }
        public string name { get; set; }
        public Nullable<int> phone { get; set; }
        public string adrress { get; set; }
        public string email { get; set; }
        public string skill { get; set; }
        public string qualification { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<double> experience { get; set; }
        public string jobcategory { get; set; }
        public string gender { get; set; }
        public Nullable<double> offercurrent { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public string instagram { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string linkedin { get; set; }
    }
}
