//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekerJob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public string username { get; set; }
        public int id { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string addressdetail { get; set; }
        public string gender { get; set; }
        public string degree { get; set; }
        public Nullable<double> experience { get; set; }
        public Nullable<double> offer { get; set; }
        public string jobcategory { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> startday { get; set; }
        public Nullable<System.DateTime> endday { get; set; }
        public string description { get; set; }
        public string meta { get; set; }
    }
}
