//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekerJob
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mydb : DbContext
    {
        public Mydb()
            : base("name=Mydb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tableimagemenu> tableimagemenus { get; set; }
        public virtual DbSet<tablemenu> tablemenus { get; set; }
        public virtual DbSet<tablemenufunction> tablemenufunctions { get; set; }
        public virtual DbSet<tablemenupart> tablemenuparts { get; set; }
    }
}
