//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekerJob
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string username { get; set; }
        public int id { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string meta { get; set; }
        public Nullable<System.DateTime> daypost { get; set; }
        public string shortbref { get; set; }
        public string description { get; set; }
    }
}
