//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekerJob
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableimagemenu
    {
        public int id { get; set; }
        public string typeimage { get; set; }
        public string link { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> arrange { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    }
}
