//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekerJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddCV
    {
        public int id { get; set; }
        public string tilteBig { get; set; }
        public string titleMall { get; set; }
        public string image { get; set; }
        public string meta { get; set; }
        public string typeCv { get; set; }
    }
}
