//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekerJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveJob
    {
        public int id { get; set; }
        public Nullable<int> idjob { get; set; }
        public string usernamecandidate { get; set; }
        public Nullable<System.DateTime> saveDate { get; set; }
    }
}
